;;; Automatically generated by ‘recentf’ on Wed Aug 31 17:30:04 2022.

(setq recentf-list
      '(
        "/Users/bruno/.emacs.d/Emacs.org"
        "/Users/bruno/Projects/OrgFiles/Birthdays.org"
        "/Users/bruno/Projects/OrgFiles/Habits.org"
        "/Users/bruno/Projects/OrgFiles/Tasks.org"
        "/Users/bruno/.emacs.d/var/bookmark-default.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
